name: Build & publish images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_push_services_image:
      name: Build and publish
      runs-on: ubuntu-latest
      strategy:
        matrix:
          service: [3_14_3, 3_15_0]
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
            buildkitd-flags: --debug
        - name: Build and push image
          uses: docker/build-push-action@v2
          timeout-minutes: 10
          with:
            file: Dockerfile${{ matrix.service }}
            context: .
            build-args: |
              PROJECT=${{ matrix.service }}
            load: false
            push: false
            tags: |
              ${{ env.DOCKER_TARGET_REPOSITORY }}-${{ matrix.service }}
            outputs: type=cacheonly
            cache-from: type=gha, scope=${{ matrix.service }}
            cache-to: type=gha,mode=max, scope=${{ matrix.service }}
